# Installation guide {.unnumbered}

```{r}
#| results: "asis"
#| echo: false
source("_common.R")
```

This package can be installed using the following commands:

```{r}
#| eval = FALSE
# From CRAN - Official release:
install.packages("SCpubr")

# From GitHub - Latest stable development version:
if(!requireNamespace("devtools", quietly = TRUE)){
  install.packages("devtools") # If not installed.
}

devtools::install_github("enblacar/SCpubr", ref = "v1.1.1-dev-stable")
```

Further packages are needed in order to run the different functions:

```{r}
#| eval = FALSE
# Install CRAN packages.
cran_packages <- c("assertthat",
                   "circlize",
                   "colorspace",
                   "dplyr",
                   "ggbeeswarm",
                   "ggdist",
                   "ggExtra",
                   "ggnewscale",
                   "ggplot2",
                   "ggplotify",
                   "ggrastr",
                   "ggrepel",
                   "ggridges",
                   "ggsignif",
                   "graphics",
                   "magrittr",
                   "patchwork",
                   "pheatmap",
                   "plyr",
                   "rlang",
                   "scales",
                   "scattermore",
                   "Seurat",
                   "tibble",
                   "tidyr",
                   "forcats",
                   "Matrix",
                   "purrr",
                   "stringr",
                   "svglite",
                   "viridis")

install.packages(cran_packages)

# Install bioconductor packages.
bioconductor_packages <- c("AUCell",
                           "ComplexHeatmap",
                           "clusterProfiler",
                           "enrichplot",
                           "infercnv",
                           "Nebulosa",
                           "UCell")
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install(bioconductor_packages)

# Install github packages.
github_packages <- c("ggsankey",
                     "liana",
                     "monocle3")

if (!requireNamespace("remotes", quietly = TRUE))
    install.packages("remotes")

remotes::install_github(github_packages)
```

One can check the dependencies by running `SCpubr::state_dependencies()`.
