# Common features across plots {.unnumbered}

This page aims to list common features present across the different functions in the package (not all functions have them).

-   **Changing the font size**: Use `font.size` parameter and provide a number.
-   **Changing the font type**: Use `font.type` parameter and provide either *sans*, *mono* or *serif*.
-   **Add plot titles, subtitles and captions**: Use `plot.title`, `plot.subtitle` and `plot.caption` parameters alongside a text to display.
-   **Changing between legend types in continuous variables**: Use `legend.type` parameter and provide either *normal*, *colorbar* or *colorsteps*.
-   **Relocate the legend**: Use `legend.position` parameter alongside *top*, *bottom*, *left* or *right* or *none* to remove it.
-   **Changing the font size**: Use `font.size` parameter and provide a number.
-   **Modify default colors**: Use `colors.use` for categorical variables and `viridis_color_map` for continuous (exceptions apply, see the corresponding subsection) and provide valid color representations or a valid viridis color map. \_ **Modify the direction of continuous color scales**: Used alongsize `viridis_color_map`, provide either 1 or -1 to `viridis_direction` to specify whether the viridis scale goes from dark to light or vice versa.
-   **Plot borders around cells**: Use `plot_cell_borders` parameter alongside `border.size` and `border.color` to customize how it looks.
-   **Toggle the grid on or off**: Use `plot.grid` parameter alongside `grid.type` for the type of lines and `grid.color` for the grid color to customize it.
-   **Toggle axes on or off**: Use `plot.axes` parameter to remove the axes.
-   **Subset a continuous axis**: Use `min.cutoff` and `max.cutoff`. 
-   **Rasterize figures**: Use `raster` and `raster.dpi` parameters. It is important to play around with `pt.size` parameter in order to get the output figure right.
