project:
  type: book
  output-dir: docs

book:
  title: "SCpubr"
  reader-mode: false
  image: "./images/logo.png"
  open-graph: true
  license: "CC BY-NC-SA 4.0"

  #navbar:
  twitter-card: true
  favicon: /images/SCpubr_logo_favicon.png
  sidebar:
    title: "SCpubr  [`v2.0.0`](https://github.com/enblacar/SCpubr/blob/main/NEWS.md)"
    foreground: primary
    collapse-level: 1
    border: true
    style: docked
  page-footer:
    left: |
      Written by **Enrique Blanco Carmona**
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>
  site-url: https://enblacar.github.io/SCpubr-book/
  repo-url: https://github.com/enblacar/SCpubr/
  repo-branch: main
  search:
    location: "navbar"
    type: "textbox"
  chapters:
    - part: "Getting started"
      chapters:
      - index.qmd
      - ./preface/Installation-guide.qmd
      - ./preface/Dataset.qmd

    - part: "Functions"
      chapters:
      - ./functions/DimPlots.qmd
      - ./functions/FeaturePlots.qmd
      - ./functions/NebulosaPlots.qmd
      - ./functions/DotPlots.qmd
      - ./functions/BarPlots.qmd
      - ./functions/BoxPlots.qmd
      - ./functions/ViolinPlots.qmd
      - ./functions/BeeSwarmPlots.qmd

    - part: "Cheatsheets"
      chapters:
      - ./cheatsheets/Shared_Features.qmd
      - ./cheatsheets/DimPlots.qmd
      - ./cheatsheets/FeaturePlots.qmd
      - ./cheatsheets/NebulosaPlots.qmd
      - ./cheatsheets/DotPlots.qmd
      - ./cheatsheets/BarPlots.qmd
      - ./cheatsheets/BoxPlots.qmd
      - ./cheatsheets/ViolinPlots.qmd
      - ./cheatsheets/BeeSwarmPlots.qmd

    - part: "Appendix"
      chapters:
      - ./closing_remarks/Citation.qmd
      - ./closing_remarks/Acknowledgements.qmd




format:
  html:
    number-sections: true
    theme:
      - flatly
      - SCpubr.scss

    code-link: true
    code-block-border-left: false
    callout-appearance: default
    smooth-scroll: true
    include-in-header:
      text: <script type="text/javascript" src="./intense.js"></script>
    include-after-body:
      file: ./img_zoom.html
    grid:
      sidebar-width: 400px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem


editor: source

