project:
  type: book
  output-dir: docs

book:
  title: "SCpubr"
  reader-mode: false
  image: "./images/logo.png"
  open-graph: true
  license: "CC BY-NC-SA 4.0"

  #navbar:
  twitter-card: true
  favicon: /images/SCpubr_logo_favicon.png
  sidebar:
    title: "SCpubr  [`v3.0.1`](https://github.com/enblacar/SCpubr/blob/main/NEWS.md)"
    foreground: primary
    collapse-level: 1
    border: true
    style: docked
  page-footer:
    left: |
      Written by **Enrique Blanco Carmona**
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>
  site-url: https://enblacar.github.io/SCpubr-book/
  repo-url: https://github.com/enblacar/SCpubr/
  repo-branch: main
  search:
    location: "navbar"
    type: "textbox"
  chapters:
    - part: "Getting started"
      chapters:
      - index.qmd
      - ./00_getting_started/01_installation.qmd
      - ./00_getting_started/02_dataset.qmd
      - ./00_getting_started/03_shared_features.qmd

    - part: "Dimensionality reduction"
      chapters:
      - ./01_dimensionality_reduction/01_dimplot.qmd

    - part: "Gene expression"
      chapters:
      - ./02_gene_expression/01_featureplot.qmd
      - ./02_gene_expression/02_nebulosaplot.qmd
      - ./02_gene_expression/03_cellularstatesplot.qmd
      - ./02_gene_expression/04_dotplot.qmd
      - ./02_gene_expression/05_expressionheatmap.qmd
      - ./02_gene_expression/06_enrichmentheatmap.qmd
      - ./02_gene_expression/07_scexpressionheatmap.qmd
      - ./02_gene_expression/08_scenrichmentheatmap.qmd
      - ./02_gene_expression/09_rankedexpressionheatmap.qmd
      - ./02_gene_expression/10_rankedenrichmentheatmap.qmd

    - part: "Proportions"
      chapters:
      - ./03_proportions/01_barplot.qmd
      - ./03_proportions/02_waffleplot.qmd
      - ./03_proportions/03_alluvialplot.qmd
      - ./03_proportions/04_chorddiagramplot.qmd

    - part: "Distributions"
      chapters:
      - ./04_distributions/01_boxplot.qmd
      - ./04_distributions/02_violinplot.qmd
      - ./04_distributions/03_ridgeplot.qmd
      - ./04_distributions/04_stripplot.qmd
      - ./04_distributions/05_beeswarmplot.qmd

    - part: "Downstream analyses"
      chapters:
      - ./05_downstream_analyses/01_activityheatmap.qmd
      - ./05_downstream_analyses/02_pathwayactivityheatmap.qmd
      - ./05_downstream_analyses/03_tfactivityheatmap.qmd
      - ./05_downstream_analyses/04_correlationheatmap.qmd
      - ./05_downstream_analyses/05_groupwisedeheatmap.qmd
      - ./05_downstream_analyses/06_termenrichmentplot.qmd
      - ./05_downstream_analyses/07_volcanoplot.qmd
      - ./05_downstream_analyses/08_cnvheatmap.qmd
      - ./05_downstream_analyses/09_ligandreceptorplot.qmd
      - ./05_downstream_analyses/10_loadingsheatmap.qmd

    - part: "Accessories"
      chapters:
      - ./06_accessories/01_colorpalette.qmd
      - ./06_accessories/02_colorblindcheck.qmd
      - ./06_accessories/03_metadataheatmap.qmd
      - ./06_accessories/05_packagereport.qmd

    - part: "Appendix"
      chapters:
      - ./07_appendix/01_citation.qmd
      - ./07_appendix/02_contributing.qmd
      - ./07_appendix/03_acknowledgements.qmd
      - ./07_appendix/04_session_info.qmd




format:
  html:
    number-sections: true
    theme:
      - flatly
      - SCpubr.scss

    code-link: true
    code-block-border-left: false
    callout-appearance: default
    smooth-scroll: true
    include-in-header:
      text: <script type="text/javascript" src="./intense.js"></script>
    include-after-body:
      file: ./img_zoom.html
    grid:
      sidebar-width: 400px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem


editor: source

