---
format: 
  html:
    include-after-body:
      - ./plot_fold.html
      - ./img_zoom.html
---

# do_BarPlot()

```{r}
#| results: "asis"
#| echo: false
source("../_common.R")
suppressMessages(library("Seurat"))
```

```{r}
#| echo: false
sample <- readRDS("/b06x-isilon/b06x-g/G703/eblanco/projects/test_SC_datasets/sc_dataset.rds")
sample$modified_orig.ident <- sample(x = c("Sample_A", "Sample_B", "Sample_C"), 
                                     size = ncol(sample), 
                                     replace = TRUE, 
                                     prob = c(0.2, 0.7, 0.1))
```


## Group by a variable
```{r}
#| fig-width: 10
#| fig-height: 6
SCpubr::do_BarPlot(sample, 
                   group.by = "seurat_clusters")
```


## Split by a variable

```{r}
#| fig-width: 10
#| fig-height: 6
SCpubr::do_BarPlot(sample, 
                   group.by = "seurat_clusters",
                   split.by = "modified_orig.ident")
```

## Plot proportions

```{r}
#| fig-width: 10
#| fig-height: 6
SCpubr::do_BarPlot(sample, 
                   group.by = "seurat_clusters",
                   split.by = "modified_orig.ident",
                   position = "fill")
```

## Add total number of counts

```{r}
#| fig-width: 10
#| fig-height: 6
SCpubr::do_BarPlot(sample, 
                   group.by = "seurat_clusters",
                   split.by = "modified_orig.ident",
                   position = "fill",
                   add.n = TRUE)
```
